name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Clone đúng Flutter 3.22.0
      - name: Clone Flutter SDK
        run: |
          git clone https://github.com/flutter/flutter.git --branch 3.22.0 --depth 1 $HOME/flutter

      # 3. Thiết lập PATH để ưu tiên Flutter vừa clone
      - name: Add Flutter to PATH
        run: |
          echo "$HOME/flutter/bin" >> $GITHUB_PATH
          echo "$HOME/flutter/bin/cache/dart-sdk/bin" >> $GITHUB_PATH

      # 4. Precache để có đầy đủ công cụ cho web
      - name: Precache Flutter artifacts
        run: flutter precache --web

      # 5. Kiểm tra version đảm bảo đúng Dart 3.4.0
      - name: Check Flutter & Dart version
        run: flutter --version

      # 6. Lấy dependencies
      - name: Install dependencies
        run: flutter pub get

      # 7. Build web release
      - name: Build Flutter Web
        run: flutter build web --release

      # 8. Deploy lên GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
