name: Deploy Lunch Sharing to GitHub Pages

# Cấp phép ghi nội dung để deploy
permissions:
  contents: write
  pages: write

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.3' # thay bằng version bạn dùng

      - run: flutter build web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          # publish_branch: deploy-web # nếu bạn muốn deploy vào branch khác ngoài gh-pages 
