name: Deploy Lunch Sharing to GitHub Pages

# Cấp phép ghi nội dung để deploy
permissions:
  contents: write
  pages: write

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.3' # thay bằng version bạn dùng

      # (Tùy chọn) Cách B: Đọc từ file JSON đã commit trong repo
      - name: Build web (from file)
        run: |
          flutter build web \
            --release \
            --pwa-strategy=none \
            --base-href "/${{ github.event.repository.name }}/" \
            --dart-define-from-file=.key.json

      - name: Add SPA fallback + .nojekyll + CNAME (optional)
        run: |
          cp web/404.html build/web/ || true
          touch build/web/.nojekyll
          if [ -n "${{ secrets.CUSTOM_DOMAIN }}" ]; then echo "${{ secrets.CUSTOM_DOMAIN }}" > build/web/CNAME; fi


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          # publish_branch: deploy-web # nếu bạn muốn deploy vào branch khác ngoài gh-pages 
