name: Deploy Lunch Sharing to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.3'
          channel: stable
          cache: true

      - name: Pub get
        run: flutter pub get

      # Tính base-href theo loại repo (user.github.io vs repo thường)
      - name: Compute base-href
        shell: bash
        run: |
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          if [[ "$REPO_NAME" == *.github.io ]]; then
            echo "BASE_HREF=/" >> "$GITHUB_ENV"
          else
            echo "BASE_HREF=/$REPO_NAME/" >> "$GITHUB_ENV"
          fi
          echo "Using base-href: $BASE_HREF"

      - name: Build web (with production BASE_URL)
        run: |
          flutter build web \
            --release \
            --pwa-strategy=none \
            --base-href "${BASE_HREF}" \
            --dart-define=BASE_URL=${{ secrets.BASE_URL || 'https://lunch-sharing-be.vercel.app' }}

      # SPA fallback + nojekyll + (optional) CNAME từ secret CUSTOM_DOMAIN
      - name: Add SPA fallback and meta
        run: |
          cp build/web/index.html build/web/404.html
          touch build/web/.nojekyll
          if [ -n "${{ secrets.CUSTOM_DOMAIN }}" ]; then echo "${{ secrets.CUSTOM_DOMAIN }}" > build/web/CNAME; fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: build/web
