name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone Flutter 3.22.0 and build
        shell: bash
        run: |
          # 1. Clone đúng version
          git clone https://github.com/flutter/flutter.git --branch 3.22.0 --depth 1

          # 2. Prepend vào PATH để override Flutter có sẵn
          export PATH="$PWD/flutter/bin:$PATH"

          # 3. Xác nhận version (phải ra Flutter 3.22.0 • Dart 3.4.0)
          flutter --version

          # 4. Lấy dependencies
          flutter pub get

          # 5. Build web release
          flutter build web --release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
